version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - webnet
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - webnet

networks:
  webnet: